version: "2"
output:
  sort-order:
    - file
linters:
  enable:
    - bodyclose
    - containedctx
    - contextcheck
    - copyloopvar
    - decorder
    - dupl
    - dupword
    - durationcheck
    - errchkjson
    - errname
    - errorlint
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - makezero
    - mirror
    - nestif
    - nilerr
    - perfsprint
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - usestdlibvars
    - wastedassign
    - whitespace
  settings:
    gocyclo:
      min-complexity: 12
    nestif:
      min-complexity: 6
  exclusions:
    generated: lax
    presets:
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
