version: 2

run:
  timeout: 5m

output:
  sort-results: true
  sort-order:
    - file

linters:
  enable:
    - bodyclose
    - containedctx
    - contextcheck
    - copyloopvar
    - decorder
    - dupl
    - dupword
    - durationcheck
    - errchkjson
    - errname
    - errorlint
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - makezero
    - mirror
    - nestif
    - nilerr
    - perfsprint
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace

linters-settings:
  gocyclo:
    min-complexity: 12
  nestif:
    min-complexity: 6

issues:
  include:
    # don't suppress missing exported method/function parameters
    - EXC0012
    # don't suppress missing package level comment
    - EXC0015

formatters:
  enable:
    - goimports
